// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
)

type Db struct {
	ID         int64
	Dsn        string
	Name       string
	IsExpanded bool
	CreateTs   int64
	DeleteTs   sql.NullInt64
}

type DbTable struct {
	ID   int64
	Name string
	Spec string
}

type Kvstore struct {
	K string
	V string
}

type Session struct {
	ID       string
	DbID     int64
	Title    sql.NullString
	CreateTs int64
	DeleteTs sql.NullInt64
}

type SessionQuery struct {
	ID        int64
	SessionID string
	Qry       string
	Res       sql.NullString
	CreateTs  int64
	DeleteTs  sql.NullInt64
}
