// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cfg_DbsDelete(arg1) {
  return window['go']['app']['App']['Cfg_DbsDelete'](arg1);
}

export function Cfg_DbsGet() {
  return window['go']['app']['App']['Cfg_DbsGet']();
}

export function Cfg_DbsInsert(arg1, arg2) {
  return window['go']['app']['App']['Cfg_DbsInsert'](arg1, arg2);
}

export function Cfg_DbsSetIsExpanded(arg1, arg2) {
  return window['go']['app']['App']['Cfg_DbsSetIsExpanded'](arg1, arg2);
}

export function Cfg_DbsUpdate(arg1, arg2, arg3) {
  return window['go']['app']['App']['Cfg_DbsUpdate'](arg1, arg2, arg3);
}

export function Cfg_GetSessionQueries(arg1) {
  return window['go']['app']['App']['Cfg_GetSessionQueries'](arg1);
}

export function Cfg_LlmEnabledGet() {
  return window['go']['app']['App']['Cfg_LlmEnabledGet']();
}

export function Cfg_LlmEnabledSet(arg1) {
  return window['go']['app']['App']['Cfg_LlmEnabledSet'](arg1);
}

export function Cfg_SessionQueriesDelete(arg1) {
  return window['go']['app']['App']['Cfg_SessionQueriesDelete'](arg1);
}

export function Cfg_SessionQueriesInsert(arg1, arg2, arg3) {
  return window['go']['app']['App']['Cfg_SessionQueriesInsert'](arg1, arg2, arg3);
}

export function Cfg_SessionQueriesUpdateAnalyze(arg1, arg2) {
  return window['go']['app']['App']['Cfg_SessionQueriesUpdateAnalyze'](arg1, arg2);
}

export function Cfg_SessionQueriesUpdateExplain(arg1, arg2) {
  return window['go']['app']['App']['Cfg_SessionQueriesUpdateExplain'](arg1, arg2);
}

export function Cfg_SessionQueriesUpdateRes(arg1, arg2, arg3) {
  return window['go']['app']['App']['Cfg_SessionQueriesUpdateRes'](arg1, arg2, arg3);
}

export function Cfg_SessionsDelete(arg1) {
  return window['go']['app']['App']['Cfg_SessionsDelete'](arg1);
}

export function Cfg_SessionsGet() {
  return window['go']['app']['App']['Cfg_SessionsGet']();
}

export function Cfg_SessionsInsert(arg1) {
  return window['go']['app']['App']['Cfg_SessionsInsert'](arg1);
}

export function Cfg_SessionsUpdate(arg1, arg2) {
  return window['go']['app']['App']['Cfg_SessionsUpdate'](arg1, arg2);
}

export function Cfg_WinBoundsGet() {
  return window['go']['app']['App']['Cfg_WinBoundsGet']();
}

export function Cfg_WinBoundsSet(arg1) {
  return window['go']['app']['App']['Cfg_WinBoundsSet'](arg1);
}

export function Dbs_GetSchema(arg1, arg2) {
  return window['go']['app']['App']['Dbs_GetSchema'](arg1, arg2);
}

export function Dbs_Query(arg1, arg2) {
  return window['go']['app']['App']['Dbs_Query'](arg1, arg2);
}

export function Llm_Autocomplete(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Llm_Autocomplete'](arg1, arg2, arg3, arg4);
}

export function Llm_Close() {
  return window['go']['app']['App']['Llm_Close']();
}

export function Llm_Init() {
  return window['go']['app']['App']['Llm_Init']();
}

export function Llm_Prime(arg1, arg2) {
  return window['go']['app']['App']['Llm_Prime'](arg1, arg2);
}

export function Llm_SetSchema(arg1, arg2) {
  return window['go']['app']['App']['Llm_SetSchema'](arg1, arg2);
}

export function Llm_StatusGet() {
  return window['go']['app']['App']['Llm_StatusGet']();
}

export function Utils_ExportRows(arg1, arg2) {
  return window['go']['app']['App']['Utils_ExportRows'](arg1, arg2);
}
