-- +goose Up

CREATE TABLE IF NOT EXISTS kvstore (
  k TEXT PRIMARY KEY,
  v TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS dbs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dsn TEXT NOT NULL,
  name TEXT NOT NULL,
  is_expanded BOOLEAN NOT NULL DEFAULT FALSE,
  create_ts INTEGER NOT NULL DEFAULT(UNIXEPOCH()),
  delete_ts INTEGER
);

CREATE TABLE IF NOT EXISTS db_tables (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  spec TEXT NOT NULL,
  UNIQUE (id, name)
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  db_id INTEGER NOT NULL,
  title TEXT,
  create_ts INTEGER NOT NULL DEFAULT(UNIXEPOCH()),
  delete_ts INTEGER
);

CREATE TABLE IF NOT EXISTS session_queries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT NOT NULL,
  qry TEXT NOT NULL,
  res TEXT,
  create_ts INTEGER NOT NULL DEFAULT(UNIXEPOCH()),
  delete_ts INTEGER
);